default_color_bg=black
default_color_fg=bright_white
dialog_attr=
dialog_attr_selected=reverse
dialog_color_bg=black
dialog_color_fg=white
dialog_shaded_color_bg=black
dialog_shaded_color_fg=gray
entry_attr=
entry_color_bg=black
entry_color_fg=bright_white
help_attr=bold
help_color_bg=blue
help_color_fg=bright_white
history_name_attr=bold
history_name_attr_selected=reverse
history_name_recv_color_bg=black
history_name_recv_color_fg=bright_cyan
history_name_recv_group_color_bg=black
history_name_recv_group_color_fg=bright_magenta
history_name_sent_color_bg=black
history_name_sent_color_fg=bright_green
history_text_attachment_color_bg=black
history_text_attachment_color_fg=bright_blue
history_text_attr=
history_text_attr_selected=reverse
history_text_quoted_color_bg=black
history_text_quoted_color_fg=gray
history_text_reaction_color_bg=black
history_text_reaction_color_fg=bright_yellow
history_text_recv_color_bg=black
history_text_recv_color_fg=white
history_text_recv_group_color_bg=black
history_text_recv_group_color_fg=white
history_text_sent_color_bg=black
history_text_sent_color_fg=bright_white
list_attr=
list_attr_selected=reverse
list_color_bg=black
list_color_fg=white
list_color_unread_bg=black
list_color_unread_fg=bright_yellow
listborder_attr=
listborder_color_bg=black
listborder_color_fg=gray
status_attr=bold
status_color_bg=black
status_color_fg=bright_cyan
top_attr=bold
top_color_bg=blue
top_color_fg=bright_white
