### Colors

bold="bold"
hl_color_1="colour15"
hl_color_2="colour17"
hl_color_3="colour18"

%if "#{==:#{client_termname},linux}"
bold=""
hl_color_1="brightwhite"
hl_color_2="magenta"
hl_color_3="brightblack"
%endif

datetime="#[default,fg=brightblack,bg=black,nobold] %d/%m #[fg=white,$bold]%H:%M"
session_name="#[default,bg=yellow,fg=black] #S"

set -g mode-style "default,bg=yellow,fg=black,$bold"
set -g clock-mode-colour "yellow"

set -g message-style "default,bg=yellow,fg=black,$bold"
set -g message-command-style "default,bg=yellow,fg=black,$bold"

set -g pane-border-style "default,fg=$hl_color_3"
set -g pane-active-border-style "default,fg=$hl_color_1"

set -g status-style "default,bg=$hl_color_3,fg=white"

default_window_style="#[default,bg=black,fg=brightblack]"
current_window_style="#[default,bg=black,fg=brightwhite,$bold]"
zoomed_window_style="#[default,bg=red,fg=grey]"

set -g window-status-format "$default_window_style #I #W "
set -g window-status-current-format "#{?window_zoomed_flag,#{l:$zoomed_window_style} #I #W*,#{l:$current_window_style} #I #W} "

### Misc

set -g status-interval 1
set -g status-position top
set -g status-justify left

set -g status-left ""
set -g status-left-length 20

set -g status-right "$session_name $datetime"
set -g status-right-length 50
