### Visual + Copy mode
set -g mode-keys vi

# IMPORTANT: Terminal emulator must be OSC 52 complaiant, like Alacritty
set -s set-clipboard on

bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection-and-cancel
bind -T copy-mode-vi Enter send -X copy-selection-and-cancel

if-shell "uname | grep -q Darwin" \
    'set-option -g @copy_cmd "pbcopy"' \
    'set-option -g @copy_cmd "wl-copy"'

bind y run 'tmux capture-pane -p -S - | #{@copy_cmd}' \; display "Pane fully yanked to clipboard!"
