# IMPORTANT: duplications (eg: M-G & M-S-G) are intentional to keep
# compatibility in multiple environments (non-GUI vs GUI terms).

### Misc bindings
bind y copy-pane

bind -n M-r reload-config
bind -n M-v enter-copy-mode
bind -n M-f resume-job

### Clear pane & history
bind BSpace clear-pane

### Auto-complete with pane contents
bind -n M-Space complete-from-pane

### Pop-up shell & other "quick fire" actions
bind -n M-Enter open-shell
bind -n M-d open-todo
bind -n M-t edit-tmux-shortcuts
bind -n M-G open-gitui
bind -n M-S-G open-gitui
bind -n M-e open-scratch
bind -n M-b open-btop

### Commands & Keybinds
bind -n M-/ open-command-prompt
bind -n M-b pick-shortcut

### Sessions, panes and windows
bind -n M-g show-pane-numbers

bind -n M-w pick-window
bind -n M-s pick-session
bind -n M-f pick-tree

bind -n M-x kill-current-pane
bind -n M-X kill-other-panes # Kill all other panes
bind -n M-S-X kill-other-panes # Kill all other panes
bind -n M-q kill-current-window
bind -n M-Q kill-other-windows
bind -n M-S-Q kill-other-windows
bind -n M-! kill-current-session
bind -n M-S-! kill-current-session

bind -n M-c new-window-here
bind -n M-C prompt-new-session
bind -n M-S-C prompt-new-session

bind -n M-z toggle-pane-zoom
bind -n M-= equalize-panes
bind -n M-, prompt-rename-session
bind -n M-m prompt-move-pane
bind -n M-M prompt-move-window
bind -n M-S-M prompt-move-window

bind -n M-I toggle-pane-sync
bind -n M-S-I toggle-pane-sync

bind -n M-\\ split-pane-horizontal
bind -n M-\- split-pane-vertical

bind -n M-Tab select-last-window

# Next/Previous session
bind -n M-] select-next-session
bind -n M-[ select-previous-session

# Last active session
bind -n M-{ select-last-session
bind -n M-S-{ select-last-session

bind -n M-h select-pane-left
bind -n M-j select-pane-down
bind -n M-k select-pane-up
bind -n M-l select-pane-right

bind -n M-H resize-pane-left
bind -n M-S-H resize-pane-left
bind -n M-J resize-pane-down
bind -n M-S-J resize-pane-down
bind -n M-K resize-pane-up
bind -n M-S-K resize-pane-up
bind -n M-L resize-pane-right
bind -n M-S-L resize-pane-right

bind -n M-1 select-window-1
bind -n M-2 select-window-2
bind -n M-3 select-window-3
bind -n M-4 select-window-4
bind -n M-5 select-window-5
bind -n M-6 select-window-6
bind -n M-7 select-window-7
bind -n M-8 select-window-8
bind -n M-9 select-window-9

if-shell "uname | grep -q Linux" \
  'bind -n M-p linux-clipboard-history'

