### Misc bindings
bind -n M-r display "Reloading..."\; source-file ~/.tmux.conf \; display "Reloaded config!"
bind -n M-v display "Copy mode ON!"\; copy-mode
bind -n M-f send-keys fg C-m

### Clear pane & history
bind BSpace send-keys -R \; send-keys C-l \; clear-history

### Auto-complete with pane contents
bind -n M-Space run-shell "~/.tmux/plugins/extrakto/scripts/open.sh \"#{pane_id}\""

### Pop-up shell & other "quick fire" actions
bind -n M-Enter display-popup -w 80% -h 80% -d "#{pane_current_path}" -E $SHELL
bind -n M-d display-popup -w 80% -h 80% -E nvim --cmd 'cd %:p:h' ~/Workspaces/github/yuriteixeira/dotfiles/TODO.md
bind -n M-t display-popup -w 80% -h 80% -E nvim --cmd 'cd %:p:h' ~/Workspaces/github/yuriteixeira/dotfiles/.tmux.shortcuts.conf
bind -n M-G display-popup -w 80% -h 80% -d "#{pane_current_path}" -E sh -c 'gitui || tmux display "No git repo in #{pane_current_path}"'
bind -n M-e display-popup -w 80% -h 80% -E nvim --cmd 'cd %:p:h' ~/Workspaces/github/yuriteixeira/notes/SCRATCH.md
bind -n M-b display-popup -w 80% -h 80% -E btop -t

### Commands & Keybinds
bind -n M-/ command-prompt
bind -n M-b list-keys

### Sessions, panes and windows
bind -n M-g display-panes

bind -n M-w choose-window
bind -n M-s choose-session
bind -n M-f choose-tree

bind -n M-x confirm-before -p "Kill pane #P? (y/n)" kill-pane
bind -n M-X kill-pane -a # Kill all other panes and windows
bind -n M-q confirm-before -p "Kill window #W? (y/n)" "if-shell '[ #{session_windows} -le 1 ]' 'if-shell \"[ \\$(tmux list-sessions | wc -l) -gt 1 ]\" \"switch-client -n; kill-window\" \"kill-window\"' 'kill-window'"
bind -n M-Q confirm-before -p "Kill other windows? (y/n)" "if-shell '[ #{session_windows} -le 1 ]' 'if-shell \"[ \\$(tmux list-sessions | wc -l) -gt 1 ]\" \"switch-client -n; kill-window -a\" \"kill-window -a\"' 'kill-window -a'"
bind -n M-! confirm-before -p "Kill session #S? (y/n)" "run-shell 'tmux switch-client -n \\; kill-session -t \"#S\"'"

bind -n M-c new-window -c "#{pane_current_path}"
bind -n M-C command-prompt -I "new-session -s "

bind -n M-z resize-pane -Z # Zoom pane
bind -n M-, command-prompt -I "#S" "rename-session -- '%%'"
bind -n M-m command-prompt -I "move-pane -t "
bind -n M-M command-prompt -I "move-window -t "

bind -n M-I setw synchronize-panes\; display "Mirror input: Sync panes toggled!"

bind -n M-\\ split-window -h -c "#{pane_current_path}"
bind -n M-\- split-window -v -c "#{pane_current_path}"

bind -n M-Tab last-window

# Next/Previous session
bind -n M-] switch-client -n
bind -n M-[ switch-client -p

# Last active session
bind -n M-{ switch-client -l

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

bind -n M-H resize-pane -L 1
bind -n M-J resize-pane -D 1
bind -n M-K resize-pane -U 1
bind -n M-L resize-pane -R 1

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
