### Misc config
set -g prefix M-a
set -g escape-time 1
set -g mouse on
set -g status on
set -g bell-action none
set -g focus-events on
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM   
set -g monitor-activity off
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off

set -g history-limit 50000
set -g display-time 3000
set -g display-panes-time 5000

set -g renumber-windows on
set -g allow-rename off
set -g base-index 1
set -g pane-base-index 1

set -g default-terminal "screen-256color"
set -sa terminal-overrides ',xterm-256color:RGB'

# Pi.dev requirements (https://pi.dev/docs/latest/tmux)
set -g extended-keys on
set -g extended-keys-format csi-u
