# IMPORTANT: DO NOT REMOVE duplicated mappings (eg: M-G & M-S-G, meaning Alt + Shift + g)
#            They are INTENTIONAL, so we can keep them working on both graphical and
#            non-graphical sessions.

# NOTE: Use regular binding whenever `-n` bindings don't work or has less prio/frequency or when
#       some group starts to emerge and you wanna make bindings more coherent.

### Full reset
unbind-key -a

### Tmux & Terminal Management
bind -n M-r reload-config
bind -n M-f resume-job
bind -n M-\/ open-command-prompt

bind k edit-tmux-keybindings

### Buffers
bind -n M-BSpace clear-pane
bind -n M-Space complete-from-pane
bind -n M-v enter-copy-mode
bind -n M-y copy-pane

### Launchers
bind -n M-Enter open-shell
bind -n M-t open-todo

bind -n M-f open-fzf-picker
bind -n M-s open-fzf-session-picker
bind -n M-w open-fzf-window-picker
bind -n M-p open-fzf-process-picker

if-shell 'uname | grep -q Linux' \
  'bind -n M-p linux-clipboard-history'

### Sessions, panes and windows
bind -n M-x kill-current-pane
bind -n M-X kill-other-panes # Kill all other panes
bind -n M-S-X kill-other-panes # Kill all other panes

bind -n M-q kill-current-window
bind -n M-Q kill-other-windows
bind -n M-S-Q kill-other-windows

bind -n M-! kill-current-session
bind -n M-S-! kill-current-session

bind -n M-c new-window-here
bind -n M-C prompt-new-session
bind -n M-S-C prompt-new-session

bind -n M-z toggle-pane-zoom
bind -n M-= equalize-panes
bind -n M-, prompt-rename-session

bind -n M-M prompt-move-window
bind -n M-S-M prompt-move-window

bind -n M-I toggle-pane-sync
bind -n M-S-I toggle-pane-sync

# Movement
bind \\ split-pane-horizontal
bind \- split-pane-vertical

bind -n M-g show-pane-numbers

bind -n M-Tab last-window
bind a last-window
bind b last-pane
bind BSpace select-last-session

bind ] select-next-session
bind [ select-prev-session

# Pane navigation
bind -n M-h select-pane-left
bind -n M-j select-pane-down
bind -n M-k select-pane-up
bind -n M-l select-pane-right

bind -n M-H resize-pane-left
bind -n M-S-H resize-pane-left
bind -n M-J resize-pane-down
bind -n M-S-J resize-pane-down
bind -n M-K resize-pane-up
bind -n M-S-K resize-pane-up
bind -n M-L resize-pane-right
bind -n M-S-L resize-pane-right

bind -n M-1 select-window-1
bind -n M-2 select-window-2
bind -n M-3 select-window-3
bind -n M-4 select-window-4
bind -n M-5 select-window-5
bind -n M-6 select-window-6
bind -n M-7 select-window-7
bind -n M-8 select-window-8
bind -n M-9 select-window-9

