# Name Service Switch configuration file.
# See nsswitch.conf(5) for details.

# IMPORTANT: After installing, diff this file to ensure we include
# all additions from upstream
#
# Restart after applying this change:
# sudo systemctl enable --now avahi-daemon

passwd: files systemd
group: files [SUCCESS=merge] systemd
shadow: files systemd
gshadow: files systemd

publickey: files

hosts: mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] files myhostname dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
